# Generated by Django 4.2.2 on 2023-06-24 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawRequestLog',
            fields=[
                ('request_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('request_timestamp_utc', models.DateTimeField()),
                ('request_text', models.CharField(max_length=8000)),
            ],
            options={
                'db_table': 'supernova_raw_request_log',
            },
        ),
        migrations.CreateModel(
            name='PacketEvent',
            fields=[
                ('request_uuid', models.OneToOneField(db_column='request_uuid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='supernova_app.rawrequestlog')),
                ('request_timestamp_utc', models.DateTimeField()),
                ('app_eui', models.CharField(max_length=16)),
                ('dc_balance', models.IntegerField()),
                ('dc_nonce', models.IntegerField()),
                ('dev_eui', models.CharField(max_length=16)),
                ('devaddr', models.CharField(max_length=8)),
                ('downlink_url', models.URLField()),
                ('fcnt', models.IntegerField()),
                ('id', models.UUIDField()),
                ('hotspot_count', models.IntegerField()),
                ('metadata_adr_allowed', models.BooleanField()),
                ('metadata_cf_list_enabled', models.BooleanField()),
                ('metadata_multi_buy', models.IntegerField()),
                ('metadata_organization_id', models.CharField(max_length=36)),
                ('metadata_preferred_hotspots', models.JSONField()),
                ('metadata_rx_delay', models.IntegerField()),
                ('metadata_rx_delay_actual', models.IntegerField()),
                ('metadata_rx_delay_state', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('payload', models.CharField(max_length=255)),
                ('payload_size', models.IntegerField()),
                ('port', models.IntegerField()),
                ('raw_packet', models.CharField(max_length=255)),
                ('replay', models.BooleanField()),
                ('reported_at', models.BigIntegerField()),
                ('type', models.CharField(max_length=255)),
                ('uuid', models.UUIDField()),
            ],
            options={
                'db_table': 'supernova_packet_event',
            },
        ),
        migrations.CreateModel(
            name='PacketEventHotspot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotspot_num_within_packet', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('frequency', models.FloatField()),
                ('hold_time', models.IntegerField()),
                ('hotspot_id', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('reported_at', models.BigIntegerField()),
                ('rssi', models.FloatField()),
                ('snr', models.FloatField()),
                ('spreading', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('request_uuid', models.ForeignKey(db_column='request_uuid', on_delete=django.db.models.deletion.CASCADE, to='supernova_app.packetevent')),
            ],
            options={
                'db_table': 'supernova_packet_event_hotspot',
                'unique_together': {('request_uuid', 'hotspot_num_within_packet')},
            },
        ),
    ]
