# Generated by Django 4.2.2 on 2023-06-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supernova_app', '0002_packetevent_request_helium_integration_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketType1',
            fields=[
                ('request_uuid', models.OneToOneField(db_column='request_uuid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='packet_type_1', serialize=False, to='supernova_app.rawrequestlog')),
                ('request_timestamp_utc', models.DateTimeField()),
                ('request_helium_integration_details', models.CharField(max_length=255, null=True)),
                ('packet_type', models.PositiveIntegerField()),
                ('millis_since_boot', models.PositiveIntegerField()),
                ('packet_seq_num', models.PositiveIntegerField()),
                ('lora_dr_value', models.PositiveIntegerField()),
                ('themistor_1_temperature_c', models.SmallIntegerField()),
                ('themistor_2_temperature_c', models.SmallIntegerField()),
                ('dht_temperature_c', models.SmallIntegerField()),
                ('dht_humidity_pct', models.SmallIntegerField()),
                ('bmp_pressure_pa', models.FloatField()),
                ('bmp_temperature_c', models.FloatField()),
                ('battery_voltage_mv', models.PositiveIntegerField()),
                ('mcu_internal_temperature_c', models.SmallIntegerField()),
                ('is_switch_rtf', models.BooleanField()),
                ('gps_latitude_degrees', models.FloatField()),
                ('gps_longitude_degrees', models.FloatField()),
                ('gps_altitude_m', models.FloatField()),
                ('gps_speed_m_per_s', models.FloatField()),
                ('gps_course_degrees', models.FloatField()),
                ('gps_satellite_count', models.PositiveIntegerField()),
                ('gps_hdop_m', models.IntegerField()),
                ('gps_fix_date_epoch_time_sec', models.PositiveIntegerField()),
                ('gps_fix_date_age_ms', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'supernova_packet_type_1',
            },
        ),
    ]
